"""empty message

Revision ID: 4c89642bf091
Revises: 
Create Date: 2022-05-31 16:48:45.506690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c89642bf091'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('burger',
    sa.Column('burgerID', sa.Integer(), nullable=False),
    sa.Column('burgerName', sa.String(length=20), nullable=False),
    sa.Column('burgerPrice', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('burgerID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('burger')
    # ### end Alembic commands ###
